site_name: 'DeFi SDK'
site_description: 'DeFi SDK Docmentation'
repo_url: https://github.com/zeriontech/defi-sdk/  

nav:
  - index.md
  - examples.md
  - architecture.md
  - interacting.md
  - Supported protocols:
    - supported-protocols/adapter-registry.md
    - supported-protocols/read-only-adapters.md
    - supported-protocols/interactive-adapters.md
  - Creating your adapters:
    - creating-your-adapters/index.md
    - creating-your-adapters/read-only-adapters.md
    - creating-your-adapters/interactive-adapters.md
  - addresses.md

theme:
  name: material
  features:
  - navigation.expand

markdown_extensions:
  - attr_list
  - md_in_html
  - meta

plugins:
  - techdocs-core

